/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	gpuv1alpha1 "github.com/ihcsim/k8s-dra/pkg/apis/applyconfiguration/gpu/v1alpha1"
	v1alpha1 "github.com/ihcsim/k8s-dra/pkg/apis/gpu/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeGPUClaimParameters implements GPUClaimParametersInterface
type FakeGPUClaimParameters struct {
	Fake *FakeGpuV1alpha1
	ns   string
}

var gpuclaimparametersResource = v1alpha1.SchemeGroupVersion.WithResource("gpuclaimparameters")

var gpuclaimparametersKind = v1alpha1.SchemeGroupVersion.WithKind("GPUClaimParameters")

// Get takes name of the gPUClaimParameters, and returns the corresponding gPUClaimParameters object, and an error if there is any.
func (c *FakeGPUClaimParameters) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.GPUClaimParameters, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(gpuclaimparametersResource, c.ns, name), &v1alpha1.GPUClaimParameters{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GPUClaimParameters), err
}

// List takes label and field selectors, and returns the list of GPUClaimParameters that match those selectors.
func (c *FakeGPUClaimParameters) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.GPUClaimParametersList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(gpuclaimparametersResource, gpuclaimparametersKind, c.ns, opts), &v1alpha1.GPUClaimParametersList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.GPUClaimParametersList{ListMeta: obj.(*v1alpha1.GPUClaimParametersList).ListMeta}
	for _, item := range obj.(*v1alpha1.GPUClaimParametersList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested gPUClaimParameters.
func (c *FakeGPUClaimParameters) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(gpuclaimparametersResource, c.ns, opts))

}

// Create takes the representation of a gPUClaimParameters and creates it.  Returns the server's representation of the gPUClaimParameters, and an error, if there is any.
func (c *FakeGPUClaimParameters) Create(ctx context.Context, gPUClaimParameters *v1alpha1.GPUClaimParameters, opts v1.CreateOptions) (result *v1alpha1.GPUClaimParameters, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(gpuclaimparametersResource, c.ns, gPUClaimParameters), &v1alpha1.GPUClaimParameters{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GPUClaimParameters), err
}

// Update takes the representation of a gPUClaimParameters and updates it. Returns the server's representation of the gPUClaimParameters, and an error, if there is any.
func (c *FakeGPUClaimParameters) Update(ctx context.Context, gPUClaimParameters *v1alpha1.GPUClaimParameters, opts v1.UpdateOptions) (result *v1alpha1.GPUClaimParameters, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(gpuclaimparametersResource, c.ns, gPUClaimParameters), &v1alpha1.GPUClaimParameters{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GPUClaimParameters), err
}

// Delete takes name of the gPUClaimParameters and deletes it. Returns an error if one occurs.
func (c *FakeGPUClaimParameters) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(gpuclaimparametersResource, c.ns, name, opts), &v1alpha1.GPUClaimParameters{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeGPUClaimParameters) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(gpuclaimparametersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.GPUClaimParametersList{})
	return err
}

// Patch applies the patch and returns the patched gPUClaimParameters.
func (c *FakeGPUClaimParameters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.GPUClaimParameters, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(gpuclaimparametersResource, c.ns, name, pt, data, subresources...), &v1alpha1.GPUClaimParameters{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GPUClaimParameters), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied gPUClaimParameters.
func (c *FakeGPUClaimParameters) Apply(ctx context.Context, gPUClaimParameters *gpuv1alpha1.GPUClaimParametersApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.GPUClaimParameters, err error) {
	if gPUClaimParameters == nil {
		return nil, fmt.Errorf("gPUClaimParameters provided to Apply must not be nil")
	}
	data, err := json.Marshal(gPUClaimParameters)
	if err != nil {
		return nil, err
	}
	name := gPUClaimParameters.Name
	if name == nil {
		return nil, fmt.Errorf("gPUClaimParameters.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(gpuclaimparametersResource, c.ns, *name, types.ApplyPatchType, data), &v1alpha1.GPUClaimParameters{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GPUClaimParameters), err
}
