/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	gpuv1alpha1 "github.com/ihcsim/k8s-dra/pkg/apis/applyconfiguration/gpu/v1alpha1"
	v1alpha1 "github.com/ihcsim/k8s-dra/pkg/apis/gpu/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeGPURequirements implements GPURequirementsInterface
type FakeGPURequirements struct {
	Fake *FakeGpuV1alpha1
	ns   string
}

var gpurequirementsResource = v1alpha1.SchemeGroupVersion.WithResource("gpurequirements")

var gpurequirementsKind = v1alpha1.SchemeGroupVersion.WithKind("GPURequirements")

// Get takes name of the gPURequirements, and returns the corresponding gPURequirements object, and an error if there is any.
func (c *FakeGPURequirements) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.GPURequirements, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(gpurequirementsResource, c.ns, name), &v1alpha1.GPURequirements{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GPURequirements), err
}

// List takes label and field selectors, and returns the list of GPURequirements that match those selectors.
func (c *FakeGPURequirements) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.GPURequirementsList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(gpurequirementsResource, gpurequirementsKind, c.ns, opts), &v1alpha1.GPURequirementsList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.GPURequirementsList{ListMeta: obj.(*v1alpha1.GPURequirementsList).ListMeta}
	for _, item := range obj.(*v1alpha1.GPURequirementsList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested gPURequirements.
func (c *FakeGPURequirements) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(gpurequirementsResource, c.ns, opts))

}

// Create takes the representation of a gPURequirements and creates it.  Returns the server's representation of the gPURequirements, and an error, if there is any.
func (c *FakeGPURequirements) Create(ctx context.Context, gPURequirements *v1alpha1.GPURequirements, opts v1.CreateOptions) (result *v1alpha1.GPURequirements, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(gpurequirementsResource, c.ns, gPURequirements), &v1alpha1.GPURequirements{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GPURequirements), err
}

// Update takes the representation of a gPURequirements and updates it. Returns the server's representation of the gPURequirements, and an error, if there is any.
func (c *FakeGPURequirements) Update(ctx context.Context, gPURequirements *v1alpha1.GPURequirements, opts v1.UpdateOptions) (result *v1alpha1.GPURequirements, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(gpurequirementsResource, c.ns, gPURequirements), &v1alpha1.GPURequirements{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GPURequirements), err
}

// Delete takes name of the gPURequirements and deletes it. Returns an error if one occurs.
func (c *FakeGPURequirements) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(gpurequirementsResource, c.ns, name, opts), &v1alpha1.GPURequirements{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeGPURequirements) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(gpurequirementsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.GPURequirementsList{})
	return err
}

// Patch applies the patch and returns the patched gPURequirements.
func (c *FakeGPURequirements) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.GPURequirements, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(gpurequirementsResource, c.ns, name, pt, data, subresources...), &v1alpha1.GPURequirements{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GPURequirements), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied gPURequirements.
func (c *FakeGPURequirements) Apply(ctx context.Context, gPURequirements *gpuv1alpha1.GPURequirementsApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.GPURequirements, err error) {
	if gPURequirements == nil {
		return nil, fmt.Errorf("gPURequirements provided to Apply must not be nil")
	}
	data, err := json.Marshal(gPURequirements)
	if err != nil {
		return nil, err
	}
	name := gPURequirements.Name
	if name == nil {
		return nil, fmt.Errorf("gPURequirements.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(gpurequirementsResource, c.ns, *name, types.ApplyPatchType, data), &v1alpha1.GPURequirements{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GPURequirements), err
}
