/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	gpuv1alpha1 "github.com/ihcsim/k8s-dra/pkg/apis/applyconfiguration/gpu/v1alpha1"
	v1alpha1 "github.com/ihcsim/k8s-dra/pkg/apis/gpu/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNodeGPUSlices implements NodeGPUSlicesInterface
type FakeNodeGPUSlices struct {
	Fake *FakeGpuV1alpha1
	ns   string
}

var nodegpuslicesResource = v1alpha1.SchemeGroupVersion.WithResource("nodegpuslices")

var nodegpuslicesKind = v1alpha1.SchemeGroupVersion.WithKind("NodeGPUSlices")

// Get takes name of the nodeGPUSlices, and returns the corresponding nodeGPUSlices object, and an error if there is any.
func (c *FakeNodeGPUSlices) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.NodeGPUSlices, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(nodegpuslicesResource, c.ns, name), &v1alpha1.NodeGPUSlices{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NodeGPUSlices), err
}

// List takes label and field selectors, and returns the list of NodeGPUSlices that match those selectors.
func (c *FakeNodeGPUSlices) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.NodeGPUSlicesList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(nodegpuslicesResource, nodegpuslicesKind, c.ns, opts), &v1alpha1.NodeGPUSlicesList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.NodeGPUSlicesList{ListMeta: obj.(*v1alpha1.NodeGPUSlicesList).ListMeta}
	for _, item := range obj.(*v1alpha1.NodeGPUSlicesList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested nodeGPUSlices.
func (c *FakeNodeGPUSlices) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(nodegpuslicesResource, c.ns, opts))

}

// Create takes the representation of a nodeGPUSlices and creates it.  Returns the server's representation of the nodeGPUSlices, and an error, if there is any.
func (c *FakeNodeGPUSlices) Create(ctx context.Context, nodeGPUSlices *v1alpha1.NodeGPUSlices, opts v1.CreateOptions) (result *v1alpha1.NodeGPUSlices, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(nodegpuslicesResource, c.ns, nodeGPUSlices), &v1alpha1.NodeGPUSlices{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NodeGPUSlices), err
}

// Update takes the representation of a nodeGPUSlices and updates it. Returns the server's representation of the nodeGPUSlices, and an error, if there is any.
func (c *FakeNodeGPUSlices) Update(ctx context.Context, nodeGPUSlices *v1alpha1.NodeGPUSlices, opts v1.UpdateOptions) (result *v1alpha1.NodeGPUSlices, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(nodegpuslicesResource, c.ns, nodeGPUSlices), &v1alpha1.NodeGPUSlices{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NodeGPUSlices), err
}

// Delete takes name of the nodeGPUSlices and deletes it. Returns an error if one occurs.
func (c *FakeNodeGPUSlices) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(nodegpuslicesResource, c.ns, name, opts), &v1alpha1.NodeGPUSlices{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNodeGPUSlices) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(nodegpuslicesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.NodeGPUSlicesList{})
	return err
}

// Patch applies the patch and returns the patched nodeGPUSlices.
func (c *FakeNodeGPUSlices) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.NodeGPUSlices, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(nodegpuslicesResource, c.ns, name, pt, data, subresources...), &v1alpha1.NodeGPUSlices{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NodeGPUSlices), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied nodeGPUSlices.
func (c *FakeNodeGPUSlices) Apply(ctx context.Context, nodeGPUSlices *gpuv1alpha1.NodeGPUSlicesApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.NodeGPUSlices, err error) {
	if nodeGPUSlices == nil {
		return nil, fmt.Errorf("nodeGPUSlices provided to Apply must not be nil")
	}
	data, err := json.Marshal(nodeGPUSlices)
	if err != nil {
		return nil, err
	}
	name := nodeGPUSlices.Name
	if name == nil {
		return nil, fmt.Errorf("nodeGPUSlices.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(nodegpuslicesResource, c.ns, *name, types.ApplyPatchType, data), &v1alpha1.NodeGPUSlices{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NodeGPUSlices), err
}
