/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	gpuv1alpha1 "github.com/ihcsim/k8s-dra/pkg/apis/applyconfiguration/gpu/v1alpha1"
	v1alpha1 "github.com/ihcsim/k8s-dra/pkg/apis/gpu/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeGPUClassParameters implements GPUClassParametersInterface
type FakeGPUClassParameters struct {
	Fake *FakeGpuV1alpha1
}

var gpuclassparametersResource = v1alpha1.SchemeGroupVersion.WithResource("gpuclassparameters")

var gpuclassparametersKind = v1alpha1.SchemeGroupVersion.WithKind("GPUClassParameters")

// Get takes name of the gPUClassParameters, and returns the corresponding gPUClassParameters object, and an error if there is any.
func (c *FakeGPUClassParameters) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.GPUClassParameters, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(gpuclassparametersResource, name), &v1alpha1.GPUClassParameters{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GPUClassParameters), err
}

// List takes label and field selectors, and returns the list of GPUClassParameters that match those selectors.
func (c *FakeGPUClassParameters) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.GPUClassParametersList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(gpuclassparametersResource, gpuclassparametersKind, opts), &v1alpha1.GPUClassParametersList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.GPUClassParametersList{ListMeta: obj.(*v1alpha1.GPUClassParametersList).ListMeta}
	for _, item := range obj.(*v1alpha1.GPUClassParametersList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested gPUClassParameters.
func (c *FakeGPUClassParameters) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(gpuclassparametersResource, opts))
}

// Create takes the representation of a gPUClassParameters and creates it.  Returns the server's representation of the gPUClassParameters, and an error, if there is any.
func (c *FakeGPUClassParameters) Create(ctx context.Context, gPUClassParameters *v1alpha1.GPUClassParameters, opts v1.CreateOptions) (result *v1alpha1.GPUClassParameters, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(gpuclassparametersResource, gPUClassParameters), &v1alpha1.GPUClassParameters{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GPUClassParameters), err
}

// Update takes the representation of a gPUClassParameters and updates it. Returns the server's representation of the gPUClassParameters, and an error, if there is any.
func (c *FakeGPUClassParameters) Update(ctx context.Context, gPUClassParameters *v1alpha1.GPUClassParameters, opts v1.UpdateOptions) (result *v1alpha1.GPUClassParameters, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(gpuclassparametersResource, gPUClassParameters), &v1alpha1.GPUClassParameters{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GPUClassParameters), err
}

// Delete takes name of the gPUClassParameters and deletes it. Returns an error if one occurs.
func (c *FakeGPUClassParameters) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(gpuclassparametersResource, name, opts), &v1alpha1.GPUClassParameters{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeGPUClassParameters) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(gpuclassparametersResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.GPUClassParametersList{})
	return err
}

// Patch applies the patch and returns the patched gPUClassParameters.
func (c *FakeGPUClassParameters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.GPUClassParameters, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(gpuclassparametersResource, name, pt, data, subresources...), &v1alpha1.GPUClassParameters{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GPUClassParameters), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied gPUClassParameters.
func (c *FakeGPUClassParameters) Apply(ctx context.Context, gPUClassParameters *gpuv1alpha1.GPUClassParametersApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.GPUClassParameters, err error) {
	if gPUClassParameters == nil {
		return nil, fmt.Errorf("gPUClassParameters provided to Apply must not be nil")
	}
	data, err := json.Marshal(gPUClassParameters)
	if err != nil {
		return nil, err
	}
	name := gPUClassParameters.Name
	if name == nil {
		return nil, fmt.Errorf("gPUClassParameters.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(gpuclassparametersResource, *name, types.ApplyPatchType, data), &v1alpha1.GPUClassParameters{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GPUClassParameters), err
}
