/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	gpuv1alpha1 "github.com/ihcsim/k8s-dra/pkg/apis/applyconfiguration/gpu/v1alpha1"
	v1alpha1 "github.com/ihcsim/k8s-dra/pkg/apis/gpu/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNodeDevices implements NodeDevicesInterface
type FakeNodeDevices struct {
	Fake *FakeGpuV1alpha1
	ns   string
}

var nodedevicesResource = v1alpha1.SchemeGroupVersion.WithResource("nodedevices")

var nodedevicesKind = v1alpha1.SchemeGroupVersion.WithKind("NodeDevices")

// Get takes name of the nodeDevices, and returns the corresponding nodeDevices object, and an error if there is any.
func (c *FakeNodeDevices) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.NodeDevices, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(nodedevicesResource, c.ns, name), &v1alpha1.NodeDevices{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NodeDevices), err
}

// List takes label and field selectors, and returns the list of NodeDevices that match those selectors.
func (c *FakeNodeDevices) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.NodeDevicesList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(nodedevicesResource, nodedevicesKind, c.ns, opts), &v1alpha1.NodeDevicesList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.NodeDevicesList{ListMeta: obj.(*v1alpha1.NodeDevicesList).ListMeta}
	for _, item := range obj.(*v1alpha1.NodeDevicesList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested nodeDevices.
func (c *FakeNodeDevices) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(nodedevicesResource, c.ns, opts))

}

// Create takes the representation of a nodeDevices and creates it.  Returns the server's representation of the nodeDevices, and an error, if there is any.
func (c *FakeNodeDevices) Create(ctx context.Context, nodeDevices *v1alpha1.NodeDevices, opts v1.CreateOptions) (result *v1alpha1.NodeDevices, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(nodedevicesResource, c.ns, nodeDevices), &v1alpha1.NodeDevices{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NodeDevices), err
}

// Update takes the representation of a nodeDevices and updates it. Returns the server's representation of the nodeDevices, and an error, if there is any.
func (c *FakeNodeDevices) Update(ctx context.Context, nodeDevices *v1alpha1.NodeDevices, opts v1.UpdateOptions) (result *v1alpha1.NodeDevices, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(nodedevicesResource, c.ns, nodeDevices), &v1alpha1.NodeDevices{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NodeDevices), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeNodeDevices) UpdateStatus(ctx context.Context, nodeDevices *v1alpha1.NodeDevices, opts v1.UpdateOptions) (*v1alpha1.NodeDevices, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(nodedevicesResource, "status", c.ns, nodeDevices), &v1alpha1.NodeDevices{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NodeDevices), err
}

// Delete takes name of the nodeDevices and deletes it. Returns an error if one occurs.
func (c *FakeNodeDevices) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(nodedevicesResource, c.ns, name, opts), &v1alpha1.NodeDevices{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNodeDevices) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(nodedevicesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.NodeDevicesList{})
	return err
}

// Patch applies the patch and returns the patched nodeDevices.
func (c *FakeNodeDevices) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.NodeDevices, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(nodedevicesResource, c.ns, name, pt, data, subresources...), &v1alpha1.NodeDevices{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NodeDevices), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied nodeDevices.
func (c *FakeNodeDevices) Apply(ctx context.Context, nodeDevices *gpuv1alpha1.NodeDevicesApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.NodeDevices, err error) {
	if nodeDevices == nil {
		return nil, fmt.Errorf("nodeDevices provided to Apply must not be nil")
	}
	data, err := json.Marshal(nodeDevices)
	if err != nil {
		return nil, err
	}
	name := nodeDevices.Name
	if name == nil {
		return nil, fmt.Errorf("nodeDevices.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(nodedevicesResource, c.ns, *name, types.ApplyPatchType, data), &v1alpha1.NodeDevices{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NodeDevices), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeNodeDevices) ApplyStatus(ctx context.Context, nodeDevices *gpuv1alpha1.NodeDevicesApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.NodeDevices, err error) {
	if nodeDevices == nil {
		return nil, fmt.Errorf("nodeDevices provided to Apply must not be nil")
	}
	data, err := json.Marshal(nodeDevices)
	if err != nil {
		return nil, err
	}
	name := nodeDevices.Name
	if name == nil {
		return nil, fmt.Errorf("nodeDevices.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(nodedevicesResource, c.ns, *name, types.ApplyPatchType, data, "status"), &v1alpha1.NodeDevices{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NodeDevices), err
}
