version: 1
env:
- CGO_ENABLED=0
goos: linux
goarch: amd64
main: ./main.go
dir: ./
# {{ .Os }} will be replaced by goos field in the config file.
# {{ .Arch }} will be replaced by goarch field in the config file.
binary: k8sdra-{{ .Os }}-{{ .Arch }}
ldflags:
- "-X main.Version={{ .Env.VERSION }}"
- "-X main.Commit={{ .Env.COMMIT }}"
- "-X main.CommitDate={{ .Env.COMMIT_DATE }}"
- "-X main.TreeState={{ .Env.TREE_STATE }}"
