/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	allocationv1alpha1 "github.com/ihcsim/k8s-dra/pkg/apis/allocation/v1alpha1"
	versioned "github.com/ihcsim/k8s-dra/pkg/apis/clientset/versioned"
	internalinterfaces "github.com/ihcsim/k8s-dra/pkg/apis/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/ihcsim/k8s-dra/pkg/apis/listers/allocation/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// NodeDeviceAllocationInformer provides access to a shared informer and lister for
// NodeDeviceAllocations.
type NodeDeviceAllocationInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.NodeDeviceAllocationLister
}

type nodeDeviceAllocationInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewNodeDeviceAllocationInformer constructs a new informer for NodeDeviceAllocation type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewNodeDeviceAllocationInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredNodeDeviceAllocationInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredNodeDeviceAllocationInformer constructs a new informer for NodeDeviceAllocation type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredNodeDeviceAllocationInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AllocationV1alpha1().NodeDeviceAllocations(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AllocationV1alpha1().NodeDeviceAllocations(namespace).Watch(context.TODO(), options)
			},
		},
		&allocationv1alpha1.NodeDeviceAllocation{},
		resyncPeriod,
		indexers,
	)
}

func (f *nodeDeviceAllocationInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredNodeDeviceAllocationInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *nodeDeviceAllocationInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&allocationv1alpha1.NodeDeviceAllocation{}, f.defaultInformer)
}

func (f *nodeDeviceAllocationInformer) Lister() v1alpha1.NodeDeviceAllocationLister {
	return v1alpha1.NewNodeDeviceAllocationLister(f.Informer().GetIndexer())
}
