/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	json "encoding/json"
	"fmt"
	"time"

	v1alpha1 "github.com/ihcsim/k8s-dra/pkg/apis/allocation/v1alpha1"
	allocationv1alpha1 "github.com/ihcsim/k8s-dra/pkg/apis/applyconfiguration/allocation/v1alpha1"
	scheme "github.com/ihcsim/k8s-dra/pkg/apis/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// NodeDeviceAllocationsGetter has a method to return a NodeDeviceAllocationInterface.
// A group's client should implement this interface.
type NodeDeviceAllocationsGetter interface {
	NodeDeviceAllocations(namespace string) NodeDeviceAllocationInterface
}

// NodeDeviceAllocationInterface has methods to work with NodeDeviceAllocation resources.
type NodeDeviceAllocationInterface interface {
	Create(ctx context.Context, nodeDeviceAllocation *v1alpha1.NodeDeviceAllocation, opts v1.CreateOptions) (*v1alpha1.NodeDeviceAllocation, error)
	Update(ctx context.Context, nodeDeviceAllocation *v1alpha1.NodeDeviceAllocation, opts v1.UpdateOptions) (*v1alpha1.NodeDeviceAllocation, error)
	UpdateStatus(ctx context.Context, nodeDeviceAllocation *v1alpha1.NodeDeviceAllocation, opts v1.UpdateOptions) (*v1alpha1.NodeDeviceAllocation, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.NodeDeviceAllocation, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.NodeDeviceAllocationList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.NodeDeviceAllocation, err error)
	Apply(ctx context.Context, nodeDeviceAllocation *allocationv1alpha1.NodeDeviceAllocationApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.NodeDeviceAllocation, err error)
	ApplyStatus(ctx context.Context, nodeDeviceAllocation *allocationv1alpha1.NodeDeviceAllocationApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.NodeDeviceAllocation, err error)
	NodeDeviceAllocationExpansion
}

// nodeDeviceAllocations implements NodeDeviceAllocationInterface
type nodeDeviceAllocations struct {
	client rest.Interface
	ns     string
}

// newNodeDeviceAllocations returns a NodeDeviceAllocations
func newNodeDeviceAllocations(c *AllocationV1alpha1Client, namespace string) *nodeDeviceAllocations {
	return &nodeDeviceAllocations{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the nodeDeviceAllocation, and returns the corresponding nodeDeviceAllocation object, and an error if there is any.
func (c *nodeDeviceAllocations) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.NodeDeviceAllocation, err error) {
	result = &v1alpha1.NodeDeviceAllocation{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("nodedeviceallocations").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of NodeDeviceAllocations that match those selectors.
func (c *nodeDeviceAllocations) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.NodeDeviceAllocationList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.NodeDeviceAllocationList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("nodedeviceallocations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested nodeDeviceAllocations.
func (c *nodeDeviceAllocations) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("nodedeviceallocations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a nodeDeviceAllocation and creates it.  Returns the server's representation of the nodeDeviceAllocation, and an error, if there is any.
func (c *nodeDeviceAllocations) Create(ctx context.Context, nodeDeviceAllocation *v1alpha1.NodeDeviceAllocation, opts v1.CreateOptions) (result *v1alpha1.NodeDeviceAllocation, err error) {
	result = &v1alpha1.NodeDeviceAllocation{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("nodedeviceallocations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(nodeDeviceAllocation).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a nodeDeviceAllocation and updates it. Returns the server's representation of the nodeDeviceAllocation, and an error, if there is any.
func (c *nodeDeviceAllocations) Update(ctx context.Context, nodeDeviceAllocation *v1alpha1.NodeDeviceAllocation, opts v1.UpdateOptions) (result *v1alpha1.NodeDeviceAllocation, err error) {
	result = &v1alpha1.NodeDeviceAllocation{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("nodedeviceallocations").
		Name(nodeDeviceAllocation.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(nodeDeviceAllocation).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *nodeDeviceAllocations) UpdateStatus(ctx context.Context, nodeDeviceAllocation *v1alpha1.NodeDeviceAllocation, opts v1.UpdateOptions) (result *v1alpha1.NodeDeviceAllocation, err error) {
	result = &v1alpha1.NodeDeviceAllocation{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("nodedeviceallocations").
		Name(nodeDeviceAllocation.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(nodeDeviceAllocation).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the nodeDeviceAllocation and deletes it. Returns an error if one occurs.
func (c *nodeDeviceAllocations) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("nodedeviceallocations").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *nodeDeviceAllocations) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("nodedeviceallocations").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched nodeDeviceAllocation.
func (c *nodeDeviceAllocations) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.NodeDeviceAllocation, err error) {
	result = &v1alpha1.NodeDeviceAllocation{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("nodedeviceallocations").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied nodeDeviceAllocation.
func (c *nodeDeviceAllocations) Apply(ctx context.Context, nodeDeviceAllocation *allocationv1alpha1.NodeDeviceAllocationApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.NodeDeviceAllocation, err error) {
	if nodeDeviceAllocation == nil {
		return nil, fmt.Errorf("nodeDeviceAllocation provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(nodeDeviceAllocation)
	if err != nil {
		return nil, err
	}
	name := nodeDeviceAllocation.Name
	if name == nil {
		return nil, fmt.Errorf("nodeDeviceAllocation.Name must be provided to Apply")
	}
	result = &v1alpha1.NodeDeviceAllocation{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("nodedeviceallocations").
		Name(*name).
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *nodeDeviceAllocations) ApplyStatus(ctx context.Context, nodeDeviceAllocation *allocationv1alpha1.NodeDeviceAllocationApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.NodeDeviceAllocation, err error) {
	if nodeDeviceAllocation == nil {
		return nil, fmt.Errorf("nodeDeviceAllocation provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(nodeDeviceAllocation)
	if err != nil {
		return nil, err
	}

	name := nodeDeviceAllocation.Name
	if name == nil {
		return nil, fmt.Errorf("nodeDeviceAllocation.Name must be provided to Apply")
	}

	result = &v1alpha1.NodeDeviceAllocation{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("nodedeviceallocations").
		Name(*name).
		SubResource("status").
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
