/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	gpuv1alpha1 "github.com/ihcsim/k8s-dra/pkg/apis/gpu/v1alpha1"
	v1 "k8s.io/api/core/v1"
)

// DeviceAllocationApplyConfiguration represents an declarative configuration of the DeviceAllocation type for use
// with apply.
type DeviceAllocationApplyConfiguration struct {
	Claim  *v1.TypedLocalObjectReference      `json:"claim,omitempty"`
	Device *GPUDeviceApplyConfiguration       `json:"devices,omitempty"`
	State  *gpuv1alpha1.DeviceAllocationState `json:"state,omitempty"`
}

// DeviceAllocationApplyConfiguration constructs an declarative configuration of the DeviceAllocation type for use with
// apply.
func DeviceAllocation() *DeviceAllocationApplyConfiguration {
	return &DeviceAllocationApplyConfiguration{}
}

// WithClaim sets the Claim field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Claim field is set to the value of the last call.
func (b *DeviceAllocationApplyConfiguration) WithClaim(value v1.TypedLocalObjectReference) *DeviceAllocationApplyConfiguration {
	b.Claim = &value
	return b
}

// WithDevice sets the Device field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Device field is set to the value of the last call.
func (b *DeviceAllocationApplyConfiguration) WithDevice(value *GPUDeviceApplyConfiguration) *DeviceAllocationApplyConfiguration {
	b.Device = value
	return b
}

// WithState sets the State field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the State field is set to the value of the last call.
func (b *DeviceAllocationApplyConfiguration) WithState(value gpuv1alpha1.DeviceAllocationState) *DeviceAllocationApplyConfiguration {
	b.State = &value
	return b
}
