/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1alpha1 "github.com/ihcsim/k8s-dra/pkg/apis/allocation/v1alpha1"
	allocationv1alpha1 "github.com/ihcsim/k8s-dra/pkg/apis/applyconfiguration/allocation/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNodeDeviceAllocations implements NodeDeviceAllocationInterface
type FakeNodeDeviceAllocations struct {
	Fake *FakeAllocationV1alpha1
	ns   string
}

var nodedeviceallocationsResource = v1alpha1.SchemeGroupVersion.WithResource("nodedeviceallocations")

var nodedeviceallocationsKind = v1alpha1.SchemeGroupVersion.WithKind("NodeDeviceAllocation")

// Get takes name of the nodeDeviceAllocation, and returns the corresponding nodeDeviceAllocation object, and an error if there is any.
func (c *FakeNodeDeviceAllocations) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.NodeDeviceAllocation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(nodedeviceallocationsResource, c.ns, name), &v1alpha1.NodeDeviceAllocation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NodeDeviceAllocation), err
}

// List takes label and field selectors, and returns the list of NodeDeviceAllocations that match those selectors.
func (c *FakeNodeDeviceAllocations) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.NodeDeviceAllocationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(nodedeviceallocationsResource, nodedeviceallocationsKind, c.ns, opts), &v1alpha1.NodeDeviceAllocationList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.NodeDeviceAllocationList{ListMeta: obj.(*v1alpha1.NodeDeviceAllocationList).ListMeta}
	for _, item := range obj.(*v1alpha1.NodeDeviceAllocationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested nodeDeviceAllocations.
func (c *FakeNodeDeviceAllocations) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(nodedeviceallocationsResource, c.ns, opts))

}

// Create takes the representation of a nodeDeviceAllocation and creates it.  Returns the server's representation of the nodeDeviceAllocation, and an error, if there is any.
func (c *FakeNodeDeviceAllocations) Create(ctx context.Context, nodeDeviceAllocation *v1alpha1.NodeDeviceAllocation, opts v1.CreateOptions) (result *v1alpha1.NodeDeviceAllocation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(nodedeviceallocationsResource, c.ns, nodeDeviceAllocation), &v1alpha1.NodeDeviceAllocation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NodeDeviceAllocation), err
}

// Update takes the representation of a nodeDeviceAllocation and updates it. Returns the server's representation of the nodeDeviceAllocation, and an error, if there is any.
func (c *FakeNodeDeviceAllocations) Update(ctx context.Context, nodeDeviceAllocation *v1alpha1.NodeDeviceAllocation, opts v1.UpdateOptions) (result *v1alpha1.NodeDeviceAllocation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(nodedeviceallocationsResource, c.ns, nodeDeviceAllocation), &v1alpha1.NodeDeviceAllocation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NodeDeviceAllocation), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeNodeDeviceAllocations) UpdateStatus(ctx context.Context, nodeDeviceAllocation *v1alpha1.NodeDeviceAllocation, opts v1.UpdateOptions) (*v1alpha1.NodeDeviceAllocation, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(nodedeviceallocationsResource, "status", c.ns, nodeDeviceAllocation), &v1alpha1.NodeDeviceAllocation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NodeDeviceAllocation), err
}

// Delete takes name of the nodeDeviceAllocation and deletes it. Returns an error if one occurs.
func (c *FakeNodeDeviceAllocations) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(nodedeviceallocationsResource, c.ns, name, opts), &v1alpha1.NodeDeviceAllocation{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNodeDeviceAllocations) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(nodedeviceallocationsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.NodeDeviceAllocationList{})
	return err
}

// Patch applies the patch and returns the patched nodeDeviceAllocation.
func (c *FakeNodeDeviceAllocations) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.NodeDeviceAllocation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(nodedeviceallocationsResource, c.ns, name, pt, data, subresources...), &v1alpha1.NodeDeviceAllocation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NodeDeviceAllocation), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied nodeDeviceAllocation.
func (c *FakeNodeDeviceAllocations) Apply(ctx context.Context, nodeDeviceAllocation *allocationv1alpha1.NodeDeviceAllocationApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.NodeDeviceAllocation, err error) {
	if nodeDeviceAllocation == nil {
		return nil, fmt.Errorf("nodeDeviceAllocation provided to Apply must not be nil")
	}
	data, err := json.Marshal(nodeDeviceAllocation)
	if err != nil {
		return nil, err
	}
	name := nodeDeviceAllocation.Name
	if name == nil {
		return nil, fmt.Errorf("nodeDeviceAllocation.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(nodedeviceallocationsResource, c.ns, *name, types.ApplyPatchType, data), &v1alpha1.NodeDeviceAllocation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NodeDeviceAllocation), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeNodeDeviceAllocations) ApplyStatus(ctx context.Context, nodeDeviceAllocation *allocationv1alpha1.NodeDeviceAllocationApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.NodeDeviceAllocation, err error) {
	if nodeDeviceAllocation == nil {
		return nil, fmt.Errorf("nodeDeviceAllocation provided to Apply must not be nil")
	}
	data, err := json.Marshal(nodeDeviceAllocation)
	if err != nil {
		return nil, err
	}
	name := nodeDeviceAllocation.Name
	if name == nil {
		return nil, fmt.Errorf("nodeDeviceAllocation.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(nodedeviceallocationsResource, c.ns, *name, types.ApplyPatchType, data, "status"), &v1alpha1.NodeDeviceAllocation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NodeDeviceAllocation), err
}
