/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	json "encoding/json"
	"fmt"
	"time"

	gpuv1alpha1 "github.com/ihcsim/k8s-dra/pkg/apis/applyconfiguration/gpu/v1alpha1"
	scheme "github.com/ihcsim/k8s-dra/pkg/apis/clientset/versioned/scheme"
	v1alpha1 "github.com/ihcsim/k8s-dra/pkg/apis/gpu/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// GPUClassParametersGetter has a method to return a GPUClassParametersInterface.
// A group's client should implement this interface.
type GPUClassParametersGetter interface {
	GPUClassParameters() GPUClassParametersInterface
}

// GPUClassParametersInterface has methods to work with GPUClassParameters resources.
type GPUClassParametersInterface interface {
	Create(ctx context.Context, gPUClassParameters *v1alpha1.GPUClassParameters, opts v1.CreateOptions) (*v1alpha1.GPUClassParameters, error)
	Update(ctx context.Context, gPUClassParameters *v1alpha1.GPUClassParameters, opts v1.UpdateOptions) (*v1alpha1.GPUClassParameters, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.GPUClassParameters, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.GPUClassParametersList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.GPUClassParameters, err error)
	Apply(ctx context.Context, gPUClassParameters *gpuv1alpha1.GPUClassParametersApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.GPUClassParameters, err error)
	GPUClassParametersExpansion
}

// gPUClassParameters implements GPUClassParametersInterface
type gPUClassParameters struct {
	client rest.Interface
}

// newGPUClassParameters returns a GPUClassParameters
func newGPUClassParameters(c *GpuV1alpha1Client) *gPUClassParameters {
	return &gPUClassParameters{
		client: c.RESTClient(),
	}
}

// Get takes name of the gPUClassParameters, and returns the corresponding gPUClassParameters object, and an error if there is any.
func (c *gPUClassParameters) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.GPUClassParameters, err error) {
	result = &v1alpha1.GPUClassParameters{}
	err = c.client.Get().
		Resource("gpuclassparameters").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of GPUClassParameters that match those selectors.
func (c *gPUClassParameters) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.GPUClassParametersList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.GPUClassParametersList{}
	err = c.client.Get().
		Resource("gpuclassparameters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested gPUClassParameters.
func (c *gPUClassParameters) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("gpuclassparameters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a gPUClassParameters and creates it.  Returns the server's representation of the gPUClassParameters, and an error, if there is any.
func (c *gPUClassParameters) Create(ctx context.Context, gPUClassParameters *v1alpha1.GPUClassParameters, opts v1.CreateOptions) (result *v1alpha1.GPUClassParameters, err error) {
	result = &v1alpha1.GPUClassParameters{}
	err = c.client.Post().
		Resource("gpuclassparameters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(gPUClassParameters).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a gPUClassParameters and updates it. Returns the server's representation of the gPUClassParameters, and an error, if there is any.
func (c *gPUClassParameters) Update(ctx context.Context, gPUClassParameters *v1alpha1.GPUClassParameters, opts v1.UpdateOptions) (result *v1alpha1.GPUClassParameters, err error) {
	result = &v1alpha1.GPUClassParameters{}
	err = c.client.Put().
		Resource("gpuclassparameters").
		Name(gPUClassParameters.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(gPUClassParameters).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the gPUClassParameters and deletes it. Returns an error if one occurs.
func (c *gPUClassParameters) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("gpuclassparameters").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *gPUClassParameters) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("gpuclassparameters").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched gPUClassParameters.
func (c *gPUClassParameters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.GPUClassParameters, err error) {
	result = &v1alpha1.GPUClassParameters{}
	err = c.client.Patch(pt).
		Resource("gpuclassparameters").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied gPUClassParameters.
func (c *gPUClassParameters) Apply(ctx context.Context, gPUClassParameters *gpuv1alpha1.GPUClassParametersApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.GPUClassParameters, err error) {
	if gPUClassParameters == nil {
		return nil, fmt.Errorf("gPUClassParameters provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(gPUClassParameters)
	if err != nil {
		return nil, err
	}
	name := gPUClassParameters.Name
	if name == nil {
		return nil, fmt.Errorf("gPUClassParameters.Name must be provided to Apply")
	}
	result = &v1alpha1.GPUClassParameters{}
	err = c.client.Patch(types.ApplyPatchType).
		Resource("gpuclassparameters").
		Name(*name).
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
