/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	json "encoding/json"
	"fmt"
	"time"

	gpuv1alpha1 "github.com/ihcsim/k8s-dra/pkg/apis/applyconfiguration/gpu/v1alpha1"
	scheme "github.com/ihcsim/k8s-dra/pkg/apis/clientset/versioned/scheme"
	v1alpha1 "github.com/ihcsim/k8s-dra/pkg/apis/gpu/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// GPUClaimParametersGetter has a method to return a GPUClaimParametersInterface.
// A group's client should implement this interface.
type GPUClaimParametersGetter interface {
	GPUClaimParameters(namespace string) GPUClaimParametersInterface
}

// GPUClaimParametersInterface has methods to work with GPUClaimParameters resources.
type GPUClaimParametersInterface interface {
	Create(ctx context.Context, gPUClaimParameters *v1alpha1.GPUClaimParameters, opts v1.CreateOptions) (*v1alpha1.GPUClaimParameters, error)
	Update(ctx context.Context, gPUClaimParameters *v1alpha1.GPUClaimParameters, opts v1.UpdateOptions) (*v1alpha1.GPUClaimParameters, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.GPUClaimParameters, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.GPUClaimParametersList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.GPUClaimParameters, err error)
	Apply(ctx context.Context, gPUClaimParameters *gpuv1alpha1.GPUClaimParametersApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.GPUClaimParameters, err error)
	GPUClaimParametersExpansion
}

// gPUClaimParameters implements GPUClaimParametersInterface
type gPUClaimParameters struct {
	client rest.Interface
	ns     string
}

// newGPUClaimParameters returns a GPUClaimParameters
func newGPUClaimParameters(c *GpuV1alpha1Client, namespace string) *gPUClaimParameters {
	return &gPUClaimParameters{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the gPUClaimParameters, and returns the corresponding gPUClaimParameters object, and an error if there is any.
func (c *gPUClaimParameters) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.GPUClaimParameters, err error) {
	result = &v1alpha1.GPUClaimParameters{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("gpuclaimparameters").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of GPUClaimParameters that match those selectors.
func (c *gPUClaimParameters) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.GPUClaimParametersList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.GPUClaimParametersList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("gpuclaimparameters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested gPUClaimParameters.
func (c *gPUClaimParameters) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("gpuclaimparameters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a gPUClaimParameters and creates it.  Returns the server's representation of the gPUClaimParameters, and an error, if there is any.
func (c *gPUClaimParameters) Create(ctx context.Context, gPUClaimParameters *v1alpha1.GPUClaimParameters, opts v1.CreateOptions) (result *v1alpha1.GPUClaimParameters, err error) {
	result = &v1alpha1.GPUClaimParameters{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("gpuclaimparameters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(gPUClaimParameters).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a gPUClaimParameters and updates it. Returns the server's representation of the gPUClaimParameters, and an error, if there is any.
func (c *gPUClaimParameters) Update(ctx context.Context, gPUClaimParameters *v1alpha1.GPUClaimParameters, opts v1.UpdateOptions) (result *v1alpha1.GPUClaimParameters, err error) {
	result = &v1alpha1.GPUClaimParameters{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("gpuclaimparameters").
		Name(gPUClaimParameters.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(gPUClaimParameters).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the gPUClaimParameters and deletes it. Returns an error if one occurs.
func (c *gPUClaimParameters) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("gpuclaimparameters").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *gPUClaimParameters) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("gpuclaimparameters").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched gPUClaimParameters.
func (c *gPUClaimParameters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.GPUClaimParameters, err error) {
	result = &v1alpha1.GPUClaimParameters{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("gpuclaimparameters").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied gPUClaimParameters.
func (c *gPUClaimParameters) Apply(ctx context.Context, gPUClaimParameters *gpuv1alpha1.GPUClaimParametersApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.GPUClaimParameters, err error) {
	if gPUClaimParameters == nil {
		return nil, fmt.Errorf("gPUClaimParameters provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(gPUClaimParameters)
	if err != nil {
		return nil, err
	}
	name := gPUClaimParameters.Name
	if name == nil {
		return nil, fmt.Errorf("gPUClaimParameters.Name must be provided to Apply")
	}
	result = &v1alpha1.GPUClaimParameters{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("gpuclaimparameters").
		Name(*name).
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
