/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	json "encoding/json"
	"fmt"
	"time"

	gpuv1alpha1 "github.com/ihcsim/k8s-dra/pkg/apis/applyconfiguration/gpu/v1alpha1"
	scheme "github.com/ihcsim/k8s-dra/pkg/apis/clientset/versioned/scheme"
	v1alpha1 "github.com/ihcsim/k8s-dra/pkg/apis/gpu/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// GPUDeviceClassParametersGetter has a method to return a GPUDeviceClassParametersInterface.
// A group's client should implement this interface.
type GPUDeviceClassParametersGetter interface {
	GPUDeviceClassParameters() GPUDeviceClassParametersInterface
}

// GPUDeviceClassParametersInterface has methods to work with GPUDeviceClassParameters resources.
type GPUDeviceClassParametersInterface interface {
	Create(ctx context.Context, gPUDeviceClassParameters *v1alpha1.GPUDeviceClassParameters, opts v1.CreateOptions) (*v1alpha1.GPUDeviceClassParameters, error)
	Update(ctx context.Context, gPUDeviceClassParameters *v1alpha1.GPUDeviceClassParameters, opts v1.UpdateOptions) (*v1alpha1.GPUDeviceClassParameters, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.GPUDeviceClassParameters, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.GPUDeviceClassParametersList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.GPUDeviceClassParameters, err error)
	Apply(ctx context.Context, gPUDeviceClassParameters *gpuv1alpha1.GPUDeviceClassParametersApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.GPUDeviceClassParameters, err error)
	GPUDeviceClassParametersExpansion
}

// gPUDeviceClassParameters implements GPUDeviceClassParametersInterface
type gPUDeviceClassParameters struct {
	client rest.Interface
}

// newGPUDeviceClassParameters returns a GPUDeviceClassParameters
func newGPUDeviceClassParameters(c *GpuV1alpha1Client) *gPUDeviceClassParameters {
	return &gPUDeviceClassParameters{
		client: c.RESTClient(),
	}
}

// Get takes name of the gPUDeviceClassParameters, and returns the corresponding gPUDeviceClassParameters object, and an error if there is any.
func (c *gPUDeviceClassParameters) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.GPUDeviceClassParameters, err error) {
	result = &v1alpha1.GPUDeviceClassParameters{}
	err = c.client.Get().
		Resource("gpudeviceclassparameters").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of GPUDeviceClassParameters that match those selectors.
func (c *gPUDeviceClassParameters) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.GPUDeviceClassParametersList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.GPUDeviceClassParametersList{}
	err = c.client.Get().
		Resource("gpudeviceclassparameters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested gPUDeviceClassParameters.
func (c *gPUDeviceClassParameters) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("gpudeviceclassparameters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a gPUDeviceClassParameters and creates it.  Returns the server's representation of the gPUDeviceClassParameters, and an error, if there is any.
func (c *gPUDeviceClassParameters) Create(ctx context.Context, gPUDeviceClassParameters *v1alpha1.GPUDeviceClassParameters, opts v1.CreateOptions) (result *v1alpha1.GPUDeviceClassParameters, err error) {
	result = &v1alpha1.GPUDeviceClassParameters{}
	err = c.client.Post().
		Resource("gpudeviceclassparameters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(gPUDeviceClassParameters).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a gPUDeviceClassParameters and updates it. Returns the server's representation of the gPUDeviceClassParameters, and an error, if there is any.
func (c *gPUDeviceClassParameters) Update(ctx context.Context, gPUDeviceClassParameters *v1alpha1.GPUDeviceClassParameters, opts v1.UpdateOptions) (result *v1alpha1.GPUDeviceClassParameters, err error) {
	result = &v1alpha1.GPUDeviceClassParameters{}
	err = c.client.Put().
		Resource("gpudeviceclassparameters").
		Name(gPUDeviceClassParameters.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(gPUDeviceClassParameters).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the gPUDeviceClassParameters and deletes it. Returns an error if one occurs.
func (c *gPUDeviceClassParameters) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("gpudeviceclassparameters").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *gPUDeviceClassParameters) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("gpudeviceclassparameters").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched gPUDeviceClassParameters.
func (c *gPUDeviceClassParameters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.GPUDeviceClassParameters, err error) {
	result = &v1alpha1.GPUDeviceClassParameters{}
	err = c.client.Patch(pt).
		Resource("gpudeviceclassparameters").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied gPUDeviceClassParameters.
func (c *gPUDeviceClassParameters) Apply(ctx context.Context, gPUDeviceClassParameters *gpuv1alpha1.GPUDeviceClassParametersApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.GPUDeviceClassParameters, err error) {
	if gPUDeviceClassParameters == nil {
		return nil, fmt.Errorf("gPUDeviceClassParameters provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(gPUDeviceClassParameters)
	if err != nil {
		return nil, err
	}
	name := gPUDeviceClassParameters.Name
	if name == nil {
		return nil, fmt.Errorf("gPUDeviceClassParameters.Name must be provided to Apply")
	}
	result = &v1alpha1.GPUDeviceClassParameters{}
	err = c.client.Patch(types.ApplyPatchType).
		Resource("gpudeviceclassparameters").
		Name(*name).
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
