/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	json "encoding/json"
	"fmt"
	"time"

	gpuv1alpha1 "github.com/ihcsim/k8s-dra/pkg/apis/applyconfiguration/gpu/v1alpha1"
	scheme "github.com/ihcsim/k8s-dra/pkg/apis/clientset/versioned/scheme"
	v1alpha1 "github.com/ihcsim/k8s-dra/pkg/apis/gpu/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// GPURequirementsGetter has a method to return a GPURequirementsInterface.
// A group's client should implement this interface.
type GPURequirementsGetter interface {
	GPURequirements(namespace string) GPURequirementsInterface
}

// GPURequirementsInterface has methods to work with GPURequirements resources.
type GPURequirementsInterface interface {
	Create(ctx context.Context, gPURequirements *v1alpha1.GPURequirements, opts v1.CreateOptions) (*v1alpha1.GPURequirements, error)
	Update(ctx context.Context, gPURequirements *v1alpha1.GPURequirements, opts v1.UpdateOptions) (*v1alpha1.GPURequirements, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.GPURequirements, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.GPURequirementsList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.GPURequirements, err error)
	Apply(ctx context.Context, gPURequirements *gpuv1alpha1.GPURequirementsApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.GPURequirements, err error)
	GPURequirementsExpansion
}

// gPURequirements implements GPURequirementsInterface
type gPURequirements struct {
	client rest.Interface
	ns     string
}

// newGPURequirements returns a GPURequirements
func newGPURequirements(c *GpuV1alpha1Client, namespace string) *gPURequirements {
	return &gPURequirements{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the gPURequirements, and returns the corresponding gPURequirements object, and an error if there is any.
func (c *gPURequirements) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.GPURequirements, err error) {
	result = &v1alpha1.GPURequirements{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("gpurequirements").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of GPURequirements that match those selectors.
func (c *gPURequirements) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.GPURequirementsList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.GPURequirementsList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("gpurequirements").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested gPURequirements.
func (c *gPURequirements) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("gpurequirements").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a gPURequirements and creates it.  Returns the server's representation of the gPURequirements, and an error, if there is any.
func (c *gPURequirements) Create(ctx context.Context, gPURequirements *v1alpha1.GPURequirements, opts v1.CreateOptions) (result *v1alpha1.GPURequirements, err error) {
	result = &v1alpha1.GPURequirements{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("gpurequirements").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(gPURequirements).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a gPURequirements and updates it. Returns the server's representation of the gPURequirements, and an error, if there is any.
func (c *gPURequirements) Update(ctx context.Context, gPURequirements *v1alpha1.GPURequirements, opts v1.UpdateOptions) (result *v1alpha1.GPURequirements, err error) {
	result = &v1alpha1.GPURequirements{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("gpurequirements").
		Name(gPURequirements.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(gPURequirements).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the gPURequirements and deletes it. Returns an error if one occurs.
func (c *gPURequirements) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("gpurequirements").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *gPURequirements) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("gpurequirements").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched gPURequirements.
func (c *gPURequirements) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.GPURequirements, err error) {
	result = &v1alpha1.GPURequirements{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("gpurequirements").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied gPURequirements.
func (c *gPURequirements) Apply(ctx context.Context, gPURequirements *gpuv1alpha1.GPURequirementsApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.GPURequirements, err error) {
	if gPURequirements == nil {
		return nil, fmt.Errorf("gPURequirements provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(gPURequirements)
	if err != nil {
		return nil, err
	}
	name := gPURequirements.Name
	if name == nil {
		return nil, fmt.Errorf("gPURequirements.Name must be provided to Apply")
	}
	result = &v1alpha1.GPURequirements{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("gpurequirements").
		Name(*name).
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
