/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	json "encoding/json"
	"fmt"
	"time"

	gpuv1alpha1 "github.com/ihcsim/k8s-dra/pkg/apis/applyconfiguration/gpu/v1alpha1"
	scheme "github.com/ihcsim/k8s-dra/pkg/apis/clientset/versioned/scheme"
	v1alpha1 "github.com/ihcsim/k8s-dra/pkg/apis/gpu/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// NodeDevicesGetter has a method to return a NodeDevicesInterface.
// A group's client should implement this interface.
type NodeDevicesGetter interface {
	NodeDevices(namespace string) NodeDevicesInterface
}

// NodeDevicesInterface has methods to work with NodeDevices resources.
type NodeDevicesInterface interface {
	Create(ctx context.Context, nodeDevices *v1alpha1.NodeDevices, opts v1.CreateOptions) (*v1alpha1.NodeDevices, error)
	Update(ctx context.Context, nodeDevices *v1alpha1.NodeDevices, opts v1.UpdateOptions) (*v1alpha1.NodeDevices, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.NodeDevices, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.NodeDevicesList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.NodeDevices, err error)
	Apply(ctx context.Context, nodeDevices *gpuv1alpha1.NodeDevicesApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.NodeDevices, err error)
	NodeDevicesExpansion
}

// nodeDevices implements NodeDevicesInterface
type nodeDevices struct {
	client rest.Interface
	ns     string
}

// newNodeDevices returns a NodeDevices
func newNodeDevices(c *GpuV1alpha1Client, namespace string) *nodeDevices {
	return &nodeDevices{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the nodeDevices, and returns the corresponding nodeDevices object, and an error if there is any.
func (c *nodeDevices) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.NodeDevices, err error) {
	result = &v1alpha1.NodeDevices{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("nodedevices").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of NodeDevices that match those selectors.
func (c *nodeDevices) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.NodeDevicesList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.NodeDevicesList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("nodedevices").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested nodeDevices.
func (c *nodeDevices) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("nodedevices").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a nodeDevices and creates it.  Returns the server's representation of the nodeDevices, and an error, if there is any.
func (c *nodeDevices) Create(ctx context.Context, nodeDevices *v1alpha1.NodeDevices, opts v1.CreateOptions) (result *v1alpha1.NodeDevices, err error) {
	result = &v1alpha1.NodeDevices{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("nodedevices").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(nodeDevices).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a nodeDevices and updates it. Returns the server's representation of the nodeDevices, and an error, if there is any.
func (c *nodeDevices) Update(ctx context.Context, nodeDevices *v1alpha1.NodeDevices, opts v1.UpdateOptions) (result *v1alpha1.NodeDevices, err error) {
	result = &v1alpha1.NodeDevices{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("nodedevices").
		Name(nodeDevices.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(nodeDevices).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the nodeDevices and deletes it. Returns an error if one occurs.
func (c *nodeDevices) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("nodedevices").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *nodeDevices) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("nodedevices").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched nodeDevices.
func (c *nodeDevices) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.NodeDevices, err error) {
	result = &v1alpha1.NodeDevices{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("nodedevices").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied nodeDevices.
func (c *nodeDevices) Apply(ctx context.Context, nodeDevices *gpuv1alpha1.NodeDevicesApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.NodeDevices, err error) {
	if nodeDevices == nil {
		return nil, fmt.Errorf("nodeDevices provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(nodeDevices)
	if err != nil {
		return nil, err
	}
	name := nodeDevices.Name
	if name == nil {
		return nil, fmt.Errorf("nodeDevices.Name must be provided to Apply")
	}
	result = &v1alpha1.NodeDevices{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("nodedevices").
		Name(*name).
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
