/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	versioned "github.com/ihcsim/k8s-dra/pkg/apis/clientset/versioned"
	gpuv1alpha1 "github.com/ihcsim/k8s-dra/pkg/apis/gpu/v1alpha1"
	internalinterfaces "github.com/ihcsim/k8s-dra/pkg/apis/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/ihcsim/k8s-dra/pkg/apis/listers/gpu/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// GPUClassParametersInformer provides access to a shared informer and lister for
// GPUClassParameters.
type GPUClassParametersInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.GPUClassParametersLister
}

type gPUClassParametersInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewGPUClassParametersInformer constructs a new informer for GPUClassParameters type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewGPUClassParametersInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredGPUClassParametersInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredGPUClassParametersInformer constructs a new informer for GPUClassParameters type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredGPUClassParametersInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.GpuV1alpha1().GPUClassParameters().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.GpuV1alpha1().GPUClassParameters().Watch(context.TODO(), options)
			},
		},
		&gpuv1alpha1.GPUClassParameters{},
		resyncPeriod,
		indexers,
	)
}

func (f *gPUClassParametersInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredGPUClassParametersInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *gPUClassParametersInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&gpuv1alpha1.GPUClassParameters{}, f.defaultInformer)
}

func (f *gPUClassParametersInformer) Lister() v1alpha1.GPUClassParametersLister {
	return v1alpha1.NewGPUClassParametersLister(f.Informer().GetIndexer())
}
