/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	versioned "github.com/ihcsim/k8s-dra/pkg/apis/clientset/versioned"
	gpuv1alpha1 "github.com/ihcsim/k8s-dra/pkg/apis/gpu/v1alpha1"
	internalinterfaces "github.com/ihcsim/k8s-dra/pkg/apis/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/ihcsim/k8s-dra/pkg/apis/listers/gpu/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// NodeGPUSlicesInformer provides access to a shared informer and lister for
// NodeGPUSlices.
type NodeGPUSlicesInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.NodeGPUSlicesLister
}

type nodeGPUSlicesInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewNodeGPUSlicesInformer constructs a new informer for NodeGPUSlices type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewNodeGPUSlicesInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredNodeGPUSlicesInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredNodeGPUSlicesInformer constructs a new informer for NodeGPUSlices type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredNodeGPUSlicesInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.GpuV1alpha1().NodeGPUSlices(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.GpuV1alpha1().NodeGPUSlices(namespace).Watch(context.TODO(), options)
			},
		},
		&gpuv1alpha1.NodeGPUSlices{},
		resyncPeriod,
		indexers,
	)
}

func (f *nodeGPUSlicesInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredNodeGPUSlicesInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *nodeGPUSlicesInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&gpuv1alpha1.NodeGPUSlices{}, f.defaultInformer)
}

func (f *nodeGPUSlicesInformer) Lister() v1alpha1.NodeGPUSlicesLister {
	return v1alpha1.NewNodeGPUSlicesLister(f.Informer().GetIndexer())
}
