name: build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.22'
    - uses: golangci/golangci-lint-action@v6
      with:
        version: v1.58
    - run: make codegen-verify
    - run: make test
    - run: make build
